[package]
name = "cornucopia"
version = "0.4.2"
edition = "2021"
license = "MIT"
description = "Generate type checked  Rust from your SQL"
homepage = "https://github.com/LouisGariepy/cornucopia"
repository = "https://github.com/LouisGariepy/cornucopia"
readme = "README.md"
categories = ["database"]
keywords = ["postgresql", "query", "generator", "sql", "tokio-postgres"]

[workspace]
members = ["examples/*"]

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
deadpool-postgres = { version = "0.10.2" }
tokio-postgres = { version = "0.7.5", features = [
    "with-serde_json-1",
    "with-time-0_3",
    "with-uuid-0_8",
    "with-eui48-1",
] }
postgres-types = { version = "0.2.2", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
time = { version = "0.3.9", features = ["parsing"] }
uuid = "0.8.2"
eui48 = "1.1.0"

thiserror = "1.0.30"
clap = { version = "3.1.9", features = ["derive"] }
pest = "2.1.3"
pest_derive = "2.1.0"
heck = "0.4.0"
async-trait = "0.1.53"
async-recursion = "1.0.0"
