[package]
name = "cornucopia"
version = "0.1.0"
edition = "2021"
license = "LICENSE.txt"
description = "Generate type checked  Rust from your SQL"
homepage = "https://github.com/LouisGariepy/cornucopia"
repository = "https://github.com/LouisGariepy/cornucopia"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
deadpool-postgres = { version = "0.10.2", features = ["serde"] }
tokio-postgres = { version = "0.7.5", features = [
    "with-serde_json-1",
    "with-time-0_3",
    "with-uuid-0_8",
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
time = "0.3.9"
uuid = "0.8.2"

thiserror = "1.0.30"
clap = { version = "3.1.8", features = ["derive"] }
pest = "2.1.3"
pest_derive = "2.1.0"
heck = "0.4.0"
