[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.21"
criterion = "0.3.5"
postgres = "0.19.3"
tokio-postgres = "0.7.6"
postgres-types = "0.2.3"
cornucopia = { path = ".." }
cornucopia_client = { path = "../cornucopia_client" }
diesel = { version = "2.0.0-rc.0", features = ["postgres"] }

[build-dependencies]
cornucopia = { path = ".." }

[[bench]]
name = "bench"
harness = false
