[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3.5"
postgres = "0.19.3"
postgres-types = "0.2.3"
cornucopia = { path = ".." }
cornucopia_client = { path = "../cornucopia_client" }

[[bench]]
name = "bench"
harness = false
