[package]
name = "codegen_template"
version = "0.1.0"
edition = "2021"
description = "A Rust code templating macro for code generation."
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
unscanny = "0.1.0"
unicode-xid = "0.2.4"