[package]
name = "auto-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
tokio-postgres = "0.7.6"
deadpool-postgres = "0.10.2"
futures = "0.3.21"
postgres-types = "0.2.3"

cornucopia_client_async = { path = "../../clients/cornucopia_client_async" }

[build-dependencies]
cornucopia = { path = "../../cornucopia" }
