[package]
name = "integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.3.0"
toml = "0.5.9"
owo-colors = "3.4.0"
serde = { version = "1.0.138", features = ["derive"] }
clap = { version = "3.2.8", features = ["derive"] }
cornucopia = { path = "../cornucopia" }
postgres = "0.19.3"